# Generated by Django 4.0.4 on 2022-04-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.price')),
                ('session_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.session')),
            ],
        ),
    ]
