# Generated by Django 4.0.4 on 2022-04-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date_start', models.DateTimeField()),
                ('appointment_hour_stop', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=80)),
                ('status', models.BooleanField(default=True)),
                ('patient_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_hour', models.TimeField()),
                ('reason', models.TextField()),
                ('action_summary', models.TextField(blank=True, default='NC')),
                ('patient_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('planning_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.planning')),
            ],
        ),
    ]
