# Generated by Django 4.0.4 on 2022-04-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='status',
        ),
    ]
