# Generated by Django 4.0.4 on 2022-04-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_adresse_unique_id'),
        ('schedule', '0003_remove_planning_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='patient_unique_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
