# Generated by Django 4.0.4 on 2022-05-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_session_appointment_hour_session_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='planning_unique_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.planning'),
        ),
    ]
