# Generated by Django 4.0.4 on 2022-04-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_adresse_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adresse_unique_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='patient.address', verbose_name='Adresse'),
        ),
    ]
