# Generated by Django 4.0.4 on 2022-04-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField(blank=True)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('additional', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=80, verbose_name='Prenom')),
                ('birth_date', models.DateField()),
                ('mail', models.EmailField(blank=True, max_length=300)),
                ('phone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('job', models.CharField(blank=True, default='NC', max_length=150, verbose_name='Profession')),
                ('glasses', models.BooleanField(blank=True, default='NC')),
                ('medical_device', models.TextField(blank=True, default='NC')),
                ('drug', models.TextField(blank=True, default='NC')),
                ('pathology', models.TextField(blank=True, default='NC')),
                ('comment', models.TextField(blank=True, default='NC')),
                ('adresse_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='patient.address', verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=80)),
                ('document_join', models.FileField(upload_to='')),
                ('comment', models.TextField(blank=True, default='NC')),
                ('patient_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='Piece jointe')),
            ],
        ),
    ]
