# Generated by Django 4.0.4 on 2022-04-21 07:00

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document_join',
            field=models.FileField(upload_to=patient.models.user_directory_path),
        ),
    ]
