# Generated by Django 4.0.4 on 2022-05-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_adresse_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='adresse_unique_id',
        ),
        migrations.AddField(
            model_name='address',
            name='patient_unique_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='patient.patient', verbose_name='patient'),
        ),
    ]
