# Generated by Django 4.0.4 on 2022-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_adresse_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='additional',
            field=models.CharField(blank=True, max_length=200, verbose_name='complément'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom de rue'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(blank=True, verbose_name='numéro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='code postal'),
        ),
    ]
