# Generated by Django 4.0.4 on 2022-05-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_address_patient_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='patient_unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='Patient Piece jointe'),
        ),
    ]
