# Generated by Django 4.0.4 on 2022-05-23 12:02

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_attachment_patient_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document_join',
            field=models.FileField(blank=True, null=True, upload_to=patient.models.user_directory_path),
        ),
    ]
