# Generated by Django 4.0.4 on 2022-05-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_patient_glasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, default='NC', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drug',
            field=models.TextField(blank=True, default='NC', verbose_name='Traitement en cours'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glasses',
            field=models.BooleanField(blank=True, default=False, verbose_name='Dispositif correctif de vision'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mail',
            field=models.EmailField(blank=True, max_length=300, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_device',
            field=models.TextField(blank=True, default='NC', verbose_name='Dispositif médical'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pathology',
            field=models.TextField(blank=True, default='NC', verbose_name='Pathologie'),
        ),
    ]
