# Generated by Django 4.0.4 on 2022-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='session_type',
            field=models.CharField(max_length=80, verbose_name='type de séance'),
        ),
    ]
