# Generated by Django 4.0.4 on 2022-04-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_planning_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='patient_name',
        ),
    ]
